var myName = "Ravil";
console.log("Моё имя " + myName);
var myAge = 29;
console.log("мне " + myAge + " лет");
var name = prompt("введите ваше имя");
console.log("Ваше имя " + name);
var age = prompt("сколько вам лет?");
console.log("вам " + age + " лет (года)");
var plus = prompt("решите задачу 6 + 4 =");
console.log("ваш ответ " + plus);
var myPlus = "6 + 4 = " + (6 + 4);
console.log("мой ответ " + myPlus);
var minus = prompt("решите задачу 6 - 4 =");
console.log("ваш ответ " + minus);
var myMinus = "6 - 4 = " + (6 - 4);
console.log("мой ответ " + myMinus);
var umnojit = prompt("решите задачу 6 * 4 =");
console.log("ваш ответ " + umnojit);
var myUmnojit = "6 * 4 = " + (6 * 4);
console.log("мой ответ " + myUmnojit);
var dilit = prompt("решите задачу 6 / 2 =");
console.log("ваш ответ " + dilit);
var myDilit = "6 / 4 = " + (6 / 3);
console.log("мой ответ " + myDilit);
var ostatok = prompt("остаток диление 6 % 4 =");
console.log("ваш ответ " + ostatok);
var myOstatok = "6 % 4 = " + (6 % 4);
console.log("мой ответ " + myOstatok);
